name: Changed-files

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    outputs:
      status: ${{ steps.check-labels.outputs.status }}

    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get javascore files that have changed
        id: javascore
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            ibc:
              - 'contracts/javascore/ibc/**'
            lightclients:
              - 'contracts/javascore/lightclients/**'
            xcall-connection:
              - 'contracts/javascore/xcall-connection/**'

      - name: Check Label
        id: check-labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "semver:patch, semver:minor, semver:major"
          exit_type: success

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8

      - run: |
          echo $GITHUB_PR_LABEL_SEMVER_MAJOR

      - name: check if bump required
        if: steps.javascore.outputs.ibc_any_changed == 'true' &&
          (contains(github.event.pull_request.labels.*.name, 'semver:patch') ||
          contains(github.event.pull_request.labels.*.name, 'semver:minor') ||
          contains(github.event.pull_request.labels.*.name, 'semver:major'))
        
        run: |
          if [ -n "$GITHUB_PR_LABEL_SEMVER_MAJOR" ]; then
            echo "bump major"
            bump_type=major
          elif [ -n "$GITHUB_PR_LABEL_SEMVER_MINOR" ]; then
            echo "bump minor"
            bump_type=minor
          elif [ -n "$GITHUB_PR_LABEL_SEMVER_PATCH" ]; then
            echo "bump patch"
            bump_type=patch
          else
            echo "no bump"
          fi
          current_version=$(awk -F"'" '/^version/ {print $2}' contracts/javascore/ibc/build.gradle)
          new_version=$(bash ./calculate_next_semver.sh "$current_version" "$bump_type" )
          echo $new_version
          