name: Changed-files

on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    outputs:
      status: ${{ steps.check-labels.outputs.status }}

    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get javascore files that have changed
        id: javascore
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            ibc:
              - 'contracts/javascore/ibc/**'
            lightclients:
              - 'contracts/javascore/lightclients/**'
            xcall-connection:
              - 'contracts/javascore/xcall-connection/**'

      - name: Check Label
        id: check-labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "semver:patch, semver:minor, semver:major"
          exit_type: success

      - name: Install semver
        run: |
          # Download and install semver-cli
          curl -sLO https://github.com/fsaintjacques/semver-tool/releases/download/2.0.0/semver_linux_amd64
          chmod +x semver_linux_amd64
          sudo mv semver_linux_amd64 /usr/local/bin/semver
          /usr/local/bin/semver -h
      
      - name: check if bump required
        if: |
          steps.javascore.outputs.ibc_any_changed == 'true' && 
          (contains(github.event.pull_request.labels.*.name, 'semver:patch') ||
          contains(github.event.pull_request.labels.*.name, 'semver:minor') ||
          contains(github.event.pull_request.labels.*.name, 'semver:major'))
        run: |
          current_version=$(awk -F"'" '/^version/ {print $2}' contracts/javascore/ibc/build.gradle)
          new_version=$(semver bump minor "$current_version")
          echo $new_version
          