name: PR Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check PR labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: documentation,enhancement,bug,cicd,test,breaking-change,feature,scripts
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "semver:patch, semver:minor, semver:major"
          add_comment: true
          message: "You have missing semvers label: semver:patch, semver:minor, semver:major"